version: '3.8'
services:
  alchemy-backend:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - db_data:/app/data
      - uploads:/app/uploads/images
    environment:
      - DB_PATH=/app/data/mydatabase.db
      - OPENAI_API_KEY=${OPENAI_API_KEY}

volumes:
  db_data:
  uploads:
